// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCEQquug62TpvmycddYHCSXgDS7VwLoTk',
    appId: '1:502252082685:web:f84cbd021902771ff13594',
    messagingSenderId: '502252082685',
    projectId: 'fitflick-17e1d',
    authDomain: 'fitflick-17e1d.firebaseapp.com',
    storageBucket: 'fitflick-17e1d.firebasestorage.app',
    measurementId: 'G-RH1QLPS547',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCObmakKDx-cJS7ptBtaxfEnBauQWAqnXc',
    appId: '1:502252082685:android:4465f672f4bcf3eff13594',
    messagingSenderId: '502252082685',
    projectId: 'fitflick-17e1d',
    storageBucket: 'fitflick-17e1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwb3VWVj4U7J5TIv0YisKOhrUFXffSDU',
    appId: '1:502252082685:ios:95cb5975fe2fa29cf13594',
    messagingSenderId: '502252082685',
    projectId: 'fitflick-17e1d',
    storageBucket: 'fitflick-17e1d.firebasestorage.app',
    iosBundleId: 'com.example.fitflick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwb3VWVj4U7J5TIv0YisKOhrUFXffSDU',
    appId: '1:502252082685:ios:95cb5975fe2fa29cf13594',
    messagingSenderId: '502252082685',
    projectId: 'fitflick-17e1d',
    storageBucket: 'fitflick-17e1d.firebasestorage.app',
    iosBundleId: 'com.example.fitflick',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCEQquug62TpvmycddYHCSXgDS7VwLoTk',
    appId: '1:502252082685:web:759b41d8e5e432b7f13594',
    messagingSenderId: '502252082685',
    projectId: 'fitflick-17e1d',
    authDomain: 'fitflick-17e1d.firebaseapp.com',
    storageBucket: 'fitflick-17e1d.firebasestorage.app',
    measurementId: 'G-MC8W43DMHH',
  );
}
